# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subdistsmult <- function(subcentroids, query_chunks, M, k, cellnum) {
    .Call('_scmap_subdistsmult', PACKAGE = 'scmap', subcentroids, query_chunks, M, k, cellnum)
}

nearcs <- function(w, M, clus_ind, subclusters, dists, len) {
    .Call('_scmap_nearcs', PACKAGE = 'scmap', w, M, clus_ind, subclusters, dists, len)
}

normalise <- function(dat) {
    .Call('_scmap_normalise', PACKAGE = 'scmap', dat)
}

NNfirst <- function(w, k, subcentroids, subclusters, query_chunks, M, SqNorm) {
    .Call('_scmap_NNfirst', PACKAGE = 'scmap', w, k, subcentroids, subclusters, query_chunks, M, SqNorm)
}

NNmult <- function(w, k, subcentroids, subclusters, query_chunks, M, SqNorm, best_cells_so_far, best_distances_so_far, dataset_inds, dat_num) {
    .Call('_scmap_NNmult', PACKAGE = 'scmap', w, k, subcentroids, subclusters, query_chunks, M, SqNorm, best_cells_so_far, best_distances_so_far, dataset_inds, dat_num)
}

EuclSqNorm <- function(dat) {
    .Call('_scmap_EuclSqNorm', PACKAGE = 'scmap', dat)
}

rcpparma_hello_world <- function() {
    .Call('_scmap_rcpparma_hello_world', PACKAGE = 'scmap')
}

rcpparma_outerproduct <- function(x) {
    .Call('_scmap_rcpparma_outerproduct', PACKAGE = 'scmap', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_scmap_rcpparma_innerproduct', PACKAGE = 'scmap', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_scmap_rcpparma_bothproducts', PACKAGE = 'scmap', x)
}

